In [102]:
# A bit of setup

import numpy as np
import matplotlib.pyplot as plt

from cs231n.classifiers.neural_net import TwoLayerNet

%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'


In [30]:
num_inputs = 3
input_size = 4
X = 10 * np.random.randn(num_inputs, input_size)
X

array([[  9.61777192,   7.20153839,   6.96525617,  -7.54579169],
       [  6.12042855,  -1.97849615,   0.13419433,  -8.18813172],
       [  1.62979906, -14.60312959,   1.223357  , -20.88276549]])

In [31]:
X -= np.max(X)
scores = X
scores

array([[  0.        ,  -2.41623353,  -2.65251575, -17.16356361],
       [ -3.49734337, -11.59626807,  -9.48357759, -17.80590364],
       [ -7.98797286, -24.22090151,  -8.39441492, -30.5005374 ]])

In [32]:
expscores = np.exp(scores)
denoms = expscores.sum(axis=1)
denoms

array([1.15973090e+00, 3.03630236e-02, 5.65648415e-04])

In [33]:
denoms = np.tile(denoms, (expscores.shape[1], 1)).T
denoms

array([[1.15973090e+00, 1.15973090e+00, 1.15973090e+00, 1.15973090e+00],
       [3.03630236e-02, 3.03630236e-02, 3.03630236e-02, 3.03630236e-02],
       [5.65648415e-04, 5.65648415e-04, 5.65648415e-04, 5.65648415e-04]])

In [40]:
y = np.array([0, 1, 2])
reg=1e-1
probs = expscores / denoms
probs

array([[8.62268996e-01, 7.69636904e-02, 6.07672829e-02, 3.03111076e-08],
       [9.97190330e-01, 3.03011947e-04, 2.50604905e-03, 6.09044867e-07],
       [6.00234413e-01, 5.35117994e-08, 3.99765533e-01, 1.00285544e-10]])

In [36]:

N,C = X.shape
loss_contributors = probs[range(N), y]
loss_contributors

array([8.62268996e-01, 3.03011947e-04, 3.99765533e-01])

In [42]:
loss = -1 * np.log(loss_contributors).sum() / N
# regularization loss
loss += 0.5 * reg * np.sum(W1 * W1)
loss += 0.5 * reg * np.sum(W2 * W2)

NameError: name 'W1' is not defined