In [1]:
import numpy as np

In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())

0.4.1
True


In [10]:
x = np.random.randn(2,4)
x

array([[ 0.98611932,  0.46742887, -1.46858176, -1.0844741 ],
       [-2.18323918, -1.95986498,  0.38652153,  0.58271388]])

In [11]:
x[:, 1:] - x[:, :-1]

array([[-0.51869045, -1.93601063,  0.38410766],
       [ 0.2233742 ,  2.34638651,  0.19619235]])

In [3]:
x = [[0,4,1], [3,2,4]]
dW = np.zeros((5,6))

In [4]:
dW

array([[ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.]])

In [5]:
np.add

<ufunc 'add'>